development:
  clients:
    default:
      database: codercred_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    use_utc: true
test:
  clients:
    default:
      database: codercred_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    use_utc: true
production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
    use_utc: true
